In [2]:
import numpy as np

In [3]:
#1
a = np.random.random((10, 3))
[a[i,(np.asarray(abs(a[i] - 0.5))).argmin()] for i in range(10)]

[0.5748870356431961,
 0.4899920237275378,
 0.3010668355899633,
 0.2258420611272678,
 0.5397556145226796,
 0.401528358308753,
 0.2604959757523825,
 0.42915175200674693,
 0.7402612813843518,
 0.4999877952859342]

In [4]:
#2
a = np.random.random((6, 6))
[np.sum(a[i]) / np.min(a.T[i]) for i in range(6)]

[8.18416433672222,
 173.74974756014737,
 11.448793282151534,
 76.16947625723904,
 6.9727149012469845,
 14.315360205129366]

In [5]:
#3
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
p = np.where(x == 0)[0] + 1
np.max(x[p[p < len(x)]])

5

In [6]:
#4
x = np.ones(10)
i = np.array([0, 1, 2, 3, 5, 5, 5, 8])
x += np.bincount(i, minlength = len(x))
print(x)

[2. 2. 2. 2. 1. 4. 1. 1. 2. 1.]


In [10]:
#Здесь не до конца сделан
def kmeans(obs, k):
    centroids = obs[np.random.randint(0, len(obs), k)]
    h = np.arange(0, k)
    it = np.ones((k, len(obs)))
    it[h] = np.arange(0, len(obs))
    it = it.astype(int)
    dim1 = (obs[it, 0] - centroids[h, 0].reshape(k, 1))**2
    dim2 = (obs[it, 1] - centroids[h, 1].reshape(k, 1))**2
    print(((dim1 + dim2)**(1/2)).argmin(axis = 0))
    codebook = ((dim1 + dim2)**(1/2)).argmin(axis = 0)
    
    while(  ):
        centroids[h] = np.mean(obs[it])
        dim1 = (obs[it, 0] - centroids[h, 0].reshape(k, 1))**2
        dim2 = (obs[it, 1] - centroids[h, 1].reshape(k, 1))**2
        codebook = ((dim1 + dim2)**(1/2)).argmin(axis = 0)
    return codebook
    
x = np.array([[0, 1],[2, 3], [5, 6], [8, 10]])
kmeans(x, 2)

[1 1 1 0]


array([1, 1, 1, 0])